# Generated by Django 5.0.4 on 2024-05-03 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=1000)),
                ('article', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lessons.subjects')),
            ],
            options={
                'db_table': 'Lessons',
            },
        ),
    ]
