# Generated by Django 5.0.4 on 2024-05-04 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=700)),
                ('summary', models.TextField(max_length=2000)),
                ('article', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.topics')),
            ],
        ),
    ]
